//TAREA
//REALIZAR SU IDEA DE PROYECTO
//TECNOLOGÍAS QUE USARÁN (NODEJS, EXPRESS, JAVASCRIPT, MYSQL)
//VALOR AGREGADO
//CONCLUSIONES
//PROBLEMÁTICA
//VISIÓN
//MISIÓN
//REPOSITORIO DE GITHUB
//LOGO Y COLORES A UTILIZAR
